sudo: true
dist: trusty
git:
  depth: 3
language: java
jdk:
- oraclejdk8
os:
- linux
addons:
  apt:
    packages:
      - librxtx-java
install:
  - sudo apt-get install -y librxtx-java
  - chmod a+rx host/gradlew
script:
  - "(cd host ; gradle clean dist)"
  - "(cd host/bin ; sudo bash -x ./start.sh)"
deploy:
  - provider: bintray
    file: ".bintray.yml"
    user: $BINTRAY_USER
    key: $BINTRAY_API_KEY
    dry-run: $SKIP_BINTRAY
    on:
      all_branches: true
  - provider: releases
    skip_cleanup: true
    prerelease: false
    api_key: $GITHUB_ACCESS_TOKEN
    file_glob: true
    file: "host/*.zip"
    on:
      tags: true
